# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       ausmt

# >> macros
BuildArch: noarch
# << macros

Summary:    AUSMT
Version:    1.2.1
Release:    1
Group:      Qt/Qt
License:    TODO
URL:        http://github.com/SfietKonstantin/ausmt
Source0:    %{name}-%{version}.tar.bz2
Source100:  ausmt.yaml
Requires:   patch
Requires:   patchutils
Requires:   rpm >= 4.9.0

%description
AUSMT stands for Auto-Update System Modification Technology. AUSMT enables
patching of webOS system safely, handling the situations like OTA updates
etc.

This modified AUSMT is used by patchmanager in SailfishOS to perform system
files, just like with Preware on webOS.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/opt/ausmt
cp ausmt/ausmt-install %{buildroot}/opt/ausmt/
cp ausmt/ausmt-remove %{buildroot}/opt/ausmt/
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
/opt/ausmt
# >> files
# << files
